name: honey_classifier
description: "Honey Classification App for Thesis"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  image_picker: ^1.0.4
  camera: ^0.11.3
  image: ^4.0.17
  awesome_dialog: ^3.1.0
  tflite_v2: ^1.0.0
  permission_handler: ^12.0.1
  fl_chart: ^0.66.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/honey_model_v2.tflite
    - assets/labels.txt
    - assets/images/logo.png